import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";


const bricolageGrotesque = localFont({
  src: "../public/bricolage_grotesque.ttf",
  variable: "--font-bricolage",
  weight: "400 500 600 700 800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${bricolageGrotesque.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
